# Generated by Django 2.2.24 on 2021-11-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
